name: bar
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  call-foo:
    uses: ./.github/workflows/foo.yml
  bar:
    needs: call-foo
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
