name: baz
on:
  workflow_dispatch:
  workflow_call:
  workflow_run:
    workflows: bar
    types: completed
jobs:
  baz:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJson(github.event.workflow_run) }}" > workflow_run.json
      - uses: actions/upload-artifact@v4
        with:
          path: workflow_run.json