name: baz
run-name: ${{ github.event.workflow_run.display_title }}
on:
  workflow_dispatch:
  workflow_call:
  workflow_run:
    workflows: bar
    types: completed
jobs:
  baz:
    runs-on: ubuntu-latest
    steps:
      - name: workflow_run annotation
        if: ${{ github.event_name == 'workflow_run' }}
        run: "echo '::notice title=Deployment trigger::Triggered by workflow run: ${{ github.event.workflow_run.html_url }}'"
      - run: echo '${{ toJson(github.event.workflow_run) }}' > workflow_run.json
      - uses: actions/upload-artifact@v4
        with:
          path: workflow_run.json