name: foo
on:
  push:
    branches: main
  workflow_dispatch:
  workflow_call:
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJson(github.env) }}'
      - run: pwd
        working-directory: ${{ github.env.HOME }}
      - run: env
